SELECT
    EMPLOYEE_NUMBER AS employee_id,
    PERFORMANCE_RATING,
    PERCENT_SALARY_HIKE,
    TRAINING_TIMES_LAST_YEAR,
    TOTAL_WORKING_YEARS,
    NUM_COMPANIES_WORKED,
    YEARS_SINCE_LAST_PROMOTION,
    CONCAT(JOB_ROLE, '-', CAST(JOB_LEVEL AS STRING), '-', DEPARTMENT) AS job_id,
    CONCAT(EDUCATION_FIELD, '-', CAST(EDUCATION AS STRING), '-', MARITAL_STATUS) AS education_id
FROM GOOGLE_SHEETS.CLEAN_DATA
