SELECT
    EMPLOYEE_NUMBER AS employee_id,
    MONTHLY_INCOME,
    DISTANCE_FROM_HOME,
    YEARS_AT_COMPANY,
    YEARS_WITH_CURR_MANAGER,
    is_attrition,
    CONCAT(JOB_ROLE, '-', CAST(JOB_LEVEL AS STRING), '-', DEPARTMENT) AS job_id,
    CONCAT(EDUCATION_FIELD, '-', CAST(EDUCATION AS STRING), '-', MARITAL_STATUS) AS education_id
FROM GOOGLE_SHEETS.CLEAN_DATA
